# version: '3.8'
# services:
#   frontend:
#     build: .
#     container_name: frontend
#     ports:
#       - '3000:3000'
#     stdin_open: true
#     tty: true

#   nginx:
#     image: nginx:latest
#     build: .
#     restart: unless-stopped
#     ports:
#       - 80:80
#     volumes:
#       - ./nginx.conf:/etc/nginx/sites-available/default